#### Libraries to load

In [3]:
# Libraries
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)   # no column truncation
pd.set_option("display.max_rows", None)      # no row truncation
pd.set_option("display.width", None)         # no line-wrapping
pd.set_option("display.max_colwidth", None)

#### Path to the directory containing the dataset and the files to annotate

In [4]:
# Recover the path
directory_path = os.getcwd()
print(directory_path)

c:\Users\adeli\Documents 4-Q2\Practicas-ACE\anotacionACE\ACE Project

In [5]:
root_path = os.path.dirname(directory_path)
print(root_path)

c:\Users\adeli\Documents 4-Q2\Practicas-ACE\anotacionACE

In [6]:
# Store file names
abuse_cases_main_filepath = "casos abuso.xlsx"
abuse_cases_202_filepath = "casos abuso_207.xlsx"
abuse_cases_207_filepath = "casos abuso_207.xlsx"
abuse_cases_100_filepath = "ADVERSIDAD_SELECCION_100pacientes.xlsx"

In [7]:
# Set path to data file
abuse_cases_main_filepath = os.path.join(directory_path, 'data',abuse_cases_100_filepath )
print(abuse_cases_main_filepath)

c:\Users\adeli\Documents 4-Q2\Practicas-ACE\anotacionACE\ACE Project\data\ADVERSIDAD_SELECCION_100pacientes.xlsx

### Dataset column names translation and data check

In [8]:
# Load Abuse cases excel file and first look into data
abuse_cases_df = pd.read_excel(abuse_cases_main_filepath, na_values=["#NULL!"])
print("====== Number of samples ======")
print("Number of samples: ", len(abuse_cases_df))
print("\n====== Check NAs ======")
print(abuse_cases_df.isna().sum().to_frame(name="NA_Counts"))
abuse_cases_df.head(1)

====== Number of samples ======
Number of samples:  100

====== Check NAs ======
                                                NA_Counts
ANONIMIZED_TEMPORAL                                     0
MC                                                      0
MotivodeConsulta                                       35
Episodio                                                0
FechaEpisodio                                           1
Sexo                                                    0
FechaNacimiento                                         1
FechaToma                                               1
AntecedentesPsiquiátricos                               0
Antecedentes                                           91
ImpresionesSubjetivas                                  86
Grado                                                 100
Planificaciónsuicidareciente                           36
Grado_A                                                47
EJEIDiagnósticoCodificadoCIE                           74
EJEIDiagnóstico                                        26
Gradodedañomédicocomoresultadodelintentoactual         97
Historiafamiliardeintentosdesuicidio                   38
EJEIITranstornoPersonalidadyComportamientoL            91
EJEIITranstornoPersonalidadyComportamiento             84
Ideaciónsuicidareciente                                36
EJEIIITranstornoSomáticoCod1                          100
EJEIIITranstornoSomáticoTxt                            96
Númerodeintentosdesuicidioprevios                      34
EJEIVProblemasPsicosocialesyambientales                96
TRATAMIENTOALALTA                                      10
EXPLORACIÓNPSICOPATOLÓGICA                             63
Ultimo_Episodio                                         0
Num_Episodios                                           0

,ANONIMIZED_TEMPORAL,MC,MotivodeConsulta,Episodio,FechaEpisodio,Sexo,FechaNacimiento,FechaToma,AntecedentesPsiquiátricos,Antecedentes,ImpresionesSubjetivas,Grado,Planificaciónsuicidareciente,Grado_A,EJEIDiagnósticoCodificadoCIE,EJEIDiagnóstico,Gradodedañomédicocomoresultadodelintentoactual,Historiafamiliardeintentosdesuicidio,EJEIITranstornoPersonalidadyComportamientoL,EJEIITranstornoPersonalidadyComportamiento,Ideaciónsuicidareciente,EJEIIITranstornoSomáticoCod1,EJEIIITranstornoSomáticoTxt,Númerodeintentosdesuicidioprevios,EJEIVProblemasPsicosocialesyambientales,TRATAMIENTOALALTA,EXPLORACIÓNPSICOPATOLÓGICA,Ultimo_Episodio,Num_Episodios
0,93863,REVISION PRIMERA PSICOLOGIA,Revisión Psiquiatrica,C2017,2017-05-30 09:30:00,M,1966-03-07,2017-05-30 09:36:07,"Vive en Madrid desde Octubre de 2016. Previamente vivia en Tenerife.\ntiroidectomia totoal con paratiroidectomia en 1998 por bocio multinodular. en tto con eutirox, refiere con ultimso controles en rango.\nQx fibroadenoma en mama izquierda en 2007\nHTA\nen 2015 laparotomia exploradora con salpiguectomia y ooforectomia derecha parcial + anexectomia izquierdamastopatia fribroquistica. hizo una peritonitis secundarias\nendometriosis\nsd.adherencial pelvico\ndispaneuria\nescoliosis\nConsulta psiquiatrica en 2009 por ""irritabilidad, sentimiento de rabia, ansiedad, modalidades histrionicas en la expresividad verbal"". Se mencionan asimismo tratamiento con depakine, rivotril y neuleptil. Dx de tr.personalidad. Ultima consulta con psiquiaría en Italia en 2010.\nDos ingeso previos en psiquaitria en Italia refiere que por agresividad contra objetos. Refiere intentos autoliticos previos en el pasado, ultimo en noviembre de 2016 mediante sobreingesta que no fue atendido en urgencias\nVive sola compartiendo una habitación. Desempleada. Previamente trabajo de instructora deportiva. Refiere antecedentes de vivencias traumaticas violentas y sexuales que no quiere dar muchos detalles en la primera consulta (si reconoce haber sido testigo de el fallecimiento)\nNo consumo de tóxicos.\n\nFamilia de Sicilia. Padre le puso un nombre que su madre no quería. 1ª/5 (dos fallecidos porque la madre pegaba en el embarazo). Vida infantil entorno a la violencia. Figura de apego: tío paterno y tía materna. Salió con 21 años.",NaN,"Homosexual. Describe haber sido victoma de de violacion y de un asesinato. ""el que me violo silvaba y eso me descontrola, cuando lo oigo""",NaN,NaN,NaN,NaN,Posible TEPT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,NaN,"Sertralina 50mg 1/2 comprmido con el desayuno una semana y posteriormente aumentar a un comprmido\nRivotril 2,5mg 0-25gotas-0\nCita con psicología y conmigo\n\n05/05/2017\nEscitalopram 10mg comprmido con el desayuno una semana y posteriormente aumentar a un comprmido\nRivotril 2,5mg 0-25gotas-0\nCita de revisión",NaN,0,3

In [9]:
print(abuse_cases_df.columns)
abuse_cases_df.shape[1]

Index(['ANONIMIZED_TEMPORAL', 'MC', 'MotivodeConsulta', 'Episodio',
       'FechaEpisodio', 'Sexo', 'FechaNacimiento', 'FechaToma',
       'AntecedentesPsiquiátricos', 'Antecedentes', 'ImpresionesSubjetivas',
       'Grado', 'Planificaciónsuicidareciente', 'Grado_A',
       'EJEIDiagnósticoCodificadoCIE', 'EJEIDiagnóstico',
       'Gradodedañomédicocomoresultadodelintentoactual',
       'Historiafamiliardeintentosdesuicidio',
       'EJEIITranstornoPersonalidadyComportamientoL',
       'EJEIITranstornoPersonalidadyComportamiento', 'Ideaciónsuicidareciente',
       'EJEIIITranstornoSomáticoCod1', 'EJEIIITranstornoSomáticoTxt',
       'Númerodeintentosdesuicidioprevios',
       'EJEIVProblemasPsicosocialesyambientales', 'TRATAMIENTOALALTA',
       'EXPLORACIÓNPSICOPATOLÓGICA', 'Ultimo_Episodio', 'Num_Episodios'],
      dtype='object')

29

#### Translation of column names to english

In [10]:
# Create a dataframe in which to keep the columns needed
cases_df = abuse_cases_df.copy()

Translate column names to english

In [11]:
old_cols = [
    'ANONIMIZED_TEMPORAL', 'MC', 'MotivodeConsulta', 'Episodio',
       'FechaEpisodio', 'Sexo', 'FechaNacimiento', 'FechaToma',
       'AntecedentesPsiquiátricos', 'Antecedentes', 'ImpresionesSubjetivas',
       'Grado', 'Planificaciónsuicidareciente', 'Grado_A',
       'EJEIDiagnósticoCodificadoCIE', 'EJEIDiagnóstico',
       'Gradodedañomédicocomoresultadodelintentoactual',
       'Historiafamiliardeintentosdesuicidio',
       'EJEIITranstornoPersonalidadyComportamientoL',
       'EJEIITranstornoPersonalidadyComportamiento', 'Ideaciónsuicidareciente',
       'EJEIIITranstornoSomáticoCod1', 'EJEIIITranstornoSomáticoTxt',
       'Númerodeintentosdesuicidioprevios',
       'EJEIVProblemasPsicosocialesyambientales', 'TRATAMIENTOALALTA',
       'EXPLORACIÓNPSICOPATOLÓGICA', 'Ultimo_Episodio', 'Num_Episodios',
       'abuso', 'maltrato', 'infantil', 'precoz', 'violencia', 'sexual',
       'fisico', 'sum_AD']

new_cols = [
    "Anonymized_Temporal", "RC", "Reason_for_Consultation", "Episode",
    "Episode_Date", "Sex", "DoB", "Assessment_Date",
    "Psychiatric_History", "Medical_History", "Subjective_Impressions",
    "Grade", "Recent_Suicidal_Planning", "Grade_A",
    "EJEI_Coded_Diagnostic_CIE", "EJEI_Diagnostic",
    "Medical_Damage_Severity_From_Current_Attempt",
    "Family_History_of_Suicide_Attempts",
    "EJEI_Personality_and_Behavior_Disorder_L",
    "EJEI_Personality_and_Behavior_Disorder", "Recent_Suicidal_Ideation",
    "EJEI_Somatic_Disorder_Cod1", "EJEI_Somatic_Disorder_Text",
    "Number_of_Previous_Suicide_Attempts",
    "EJEI_Psychosocial_and_Environmental_Issues", "Discharge_Treatment",
    "Psychopathological_Examination", "Last_Episode", "Num_Episodes",
    "Abuse", "Maltreatment", "Childhood", "Early_AE", "Violence", "Sexual",
    "Physical", "Sum_AD"]

In [12]:
cases_df = cases_df.rename(columns=dict(zip(old_cols, new_cols)))

In [13]:
cases_df.drop(columns=[
    "Psychiatric_History", "Psychopathological_Examination"
]).tail(3)

,Anonymized_Temporal,RC,Reason_for_Consultation,Episode,Episode_Date,Sex,DoB,Assessment_Date,Medical_History,Subjective_Impressions,Grade,Recent_Suicidal_Planning,Grade_A,EJEI_Coded_Diagnostic_CIE,EJEI_Diagnostic,Medical_Damage_Severity_From_Current_Attempt,Family_History_of_Suicide_Attempts,EJEI_Personality_and_Behavior_Disorder_L,EJEI_Personality_and_Behavior_Disorder,Recent_Suicidal_Ideation,EJEI_Somatic_Disorder_Cod1,EJEI_Somatic_Disorder_Text,Number_of_Previous_Suicide_Attempts,EJEI_Psychosocial_and_Environmental_Issues,Discharge_Treatment,Last_Episode,Num_Episodes
97,24087626,REVISION PSIQUIATRIA,Depresión,C2023,2023-03-13 13:26:07,M,1958-04-20,2023-03-13 13:25:08,NaN,"Describe padre alcohólico, marido conflictivo, hijo con TUS en situación de exclusión social.\nEn varios momentos de la entrevista es difícil clarificar como se encuentra la paciente.",NaN,No,No,"F43.23- Trastorno adaptativo mixto, con ansiedad y depresión",NaN,NaN,No,NaN,NaN,No,NaN,NaN,0,NaN,"3/01/23\n\nDeprax 100 mg 1/2-0-1\n\nSertralina 50 mg 1-0-0\n\nRetirar Brintellix 5 mg. \n\nCita de revisión y cita con psicología.\n\n\n\n\n6/02/23\n\nParoxetina 20 mg , medio comprimido en el desayuno y en cinco días tomar uno entero. \nSertralina 50 mg , medio comprimido en el desayuno yen cinco días suspender\n\nDeprax 100 mg 0-0-1\n\nRivotril 0,5 mg 1-1-0\n\nCita de revisión, hasta entonces control por MAP.\n\n13/03/23 Dra Blanco \nParoxetina 20 mg 1.5 comprimido en el desayuno. Si nota mayor ansiedad con el aumento podrá volver a su pauta anterior\nDeprax 100 mg 0-0-1\nRivotril 0,5 mg 1-1-0\n\nCita de revisión, hasta entonces control por MAP.",1,5
98,24111281,1ª CONSULTA PSIQUIATRIA - C,Depresión,C2022,2022-04-28 09:23:53,M,2001-08-09,2022-04-28 10:23:37,NaN,NaN,NaN,No,No,NaN,NaN,NaN,No,NaN,Probable TP clúster B,No,NaN,NaN,0,NaN,FLUOXETINA 20MG 1-0-0\nRIVOTRIL 0.5MG 1-0-1\nSUSPENDER LEXATIN\n\nDEJO CITA,1,0
99,25745955,REVISION PSIQUIATRIA - C,NaN,C2023,2023-05-18 09:50:14,M,1969-08-31,2023-05-18 10:15:44,NaN,Historia de Acontecimientos Traumáticos:\n\n-Abandono repentino de la figura materna a los 3 años. Tenía una hermana recién nacida. Refiere que se quedaron al cago de su padre. Retomó la relación con su madre a los 22 años y han mantenido relación hasta el fallecimiento de esta en 2018. Refiere que se trataba de una relación muy complicada en la que llegó a haber agresiones.\n- Relación de pareja en la que fue maltratada durante 9 meses a los 22 años. \n- Embarazo no deseado nacimiento de una hija a los 19 años. Refiere que le obligaron a darla en adopción.\n- Embarazo y nacimiento de un hijo a los 22 años. Refiere que lo quitaron y fue criado por la madre de la paciente. Se lo llevaron a Inglaterra durante unos años. Actualmente refiere escasa elación con él.\n- Ejerció la prostitución desde los 22 a los 28. Refiere que salió de ese mundo gracias a una pareja.\n-Se encontró a su pareja muerta hace 10 años. Falleció de un infarto. \n-Padre fallecido hace 12 años de un infarto (2011). \n-Madre fallecida hace 5 años (2018).,NaN,No,No,"F43.10- Trastorno por estrés postraumático, no especificado",Síntomas disociativos.\nConsumo de sustancias.,NaN,No,NaN,NaN,No,NaN,NaN,0,NaN,18/05/23 Dra. Iza\nDeprax 100 mg 0-0-1\nParoxetina 20 mg 1-0-0\nGabapentina 100 mg 1-1-1\nBupropion 150 mg 2-0-0 \n\n\n17/04/23 Dra. Iza\nDeprax 100 mg 0-0-1\nParoxetina 20 mg 1/2-0-0 durante una semana y después subir a 1-0-0\n\n\nDeprax 100 mg 0-0-1,1,4

#### Basic data checks

In [14]:
# Ensure date format
cases_df["Episode_Date"] = pd.to_datetime(cases_df["Episode_Date"], errors="raise", format="%Y-%m-%d %H:%M:%S")
cases_df["Assessment_Date"] = pd.to_datetime(cases_df["Assessment_Date"], errors="raise", format="%Y-%m-%d %H:%M:%S")
cases_df["DoB"] =  pd.to_datetime(cases_df["DoB"], errors="raise", format="%Y-%m-%d")

In [15]:
# Separate patients whose Anonymized temporal is Nan
aux_df = cases_df[cases_df["Anonymized_Temporal"].isna()].drop(columns=[
    "Psychiatric_History", "Psychopathological_Examination"
]).head(20)

# See unique DoB, likely same patient
aux_df["DoB"].unique()

<DatetimeArray>
[]
Length: 0, dtype: datetime64[ns]

There are (likely) 10 patients with no id (Anonymized_Temporal). Need to see what to do with them (eliminate?).

In [16]:
# See possible values for several columns of interest
# RC and Reason_for_Consultation
unique_values_RC = cases_df["RC"].unique()
print(len(unique_values_RC))

37

In [17]:
unique_values_RC_txt = cases_df["Reason_for_Consultation"].unique()
print(len(unique_values_RC_txt), unique_values_RC_txt)

14 ['Revisión Psiquiatrica' nan 'Transtornos de conducta' 'Depresión'
 'Ansiedad' 'Humor lábil' 'Problemas de alimentación'
 'Problemas relac. por abuso de sustancias' 'Psicoterapia'
 'Ajuste farmacológico' 'Realización de informe' 'Pensamiento suicida'
 'Conducta suicida' 'Conducta agresiva']

Not the same information is contained on columns RC and "Reason_for_Consultation". As they are both text, need to analyze whether they could contain relevant ACE terms.

Text fields with free content: <br>
Psychiatric_History, Medical_History, Subjective_Impressions <br>

Text fields with limited number of unique values (<80): <br> Reason_for_Consultation, Episode (code), EJEI_Personality_and_Behavior_Disorder_L, EJEI_Psychosocial_and_Environmental_Issues<br>

Text fields with multiple unique values (>80): <br>
RC, EJEI_Coded_Diagnostic_CIE, EJEI_Diagnostic (not aligned with previous ones), Medical_Damage_Severity_From_Current_Attempt, EJEI_Personality_and_Behavior_Disorder, EJEI_Somatic_Disorder_Cod1,
EJEI_Somatic_Disorder_Text (not coincident with the previous one), Number_of_Previous_Suicide_Attempts, Discharge_Treatment, Psychopathological_Examination <br>

Categorical fields: <br>
Sex, Grade <br>

Date fields: <br>
Episode_Date, Assessment_Date, DoB <br>

Boolean fields: <br>
- (Si/No): Recent_Suicidal_Planning , Grade_A, Family_History_of_Suicide_Attempts, Recent_Suicidal_Ideation (also Sí) <br>
- (0/1): Last_Episode, Abuse, Maltreatment, Childhood, Early_AE, Violence, Sexual, Physical.

In [18]:
# Anonymized_Temporal unique values
unique_values = cases_df["Anonymized_Temporal"].unique()
print(len(unique_values), unique_values)

100 [   93863   203917   216535   232165   244392   246169   262678   269487
   271022   271289   305129   334931   348323   349669   365985   386053
   389030   402579   448577   464116   473217   559219   564433   595120
   608972   649848   654324   703682   706171   777318   784004   805554
   805761   808084   810687   814726   923573   941569   950325  1015281
  1024337  1025422  1042052  1069728  1072754  1077142  1086522  1113996
  1133977  1140733  1156968  1171351  1174341  1202384  1205760  1225585
  1270336  1303284  1332221  1364855  1367357  1375166  1382141  1390426
  1419477  1420993  1461127  1469042  1470079  1492571  1495588  1508243
  1513824  1518800  1531723  1559886  1858236  2100345  2173316  2191404
  2366090  4072292  4095952  4154559 11177036 15044068 20354316 20361655
 22003526 22038679 22168915 22217146 22301469 22394845 23038503 23068926
 23097069 24087626 24111281 25745955]

In [19]:
# Other fields
unique_values = cases_df["Number_of_Previous_Suicide_Attempts"].unique()
print(len(unique_values), unique_values)

17 ['7' nan '1' '0' '2' '2 + autolesiones no suicidas a lo largo de la vida'
 'Numerosos a lo latgo de la vida' '.' '3' '>10' 'Múltiples.' 'Múltiples'
 '5' 'ideas suicidas.' 'si' 'multiples' 'Más de 5']

In [ ]:
# Drop non useful columns
# Determine which:
# Text fields to keep
# Dates to keep
# Doubts: ID (likely needed to recover several patient cases after ACE classification results), Episode (medical code, can be useful if some associated to ACE terms),
# cases_df = cases_df.drop(columns=["xxx", "yyy"])

In [20]:
# Ensure there are no duplicates in the table
duplicates_mask = cases_df.duplicated(subset=["Anonymized_Temporal", "Assessment_Date"], keep=False)
num_duplicates = duplicates_mask.sum()

print(f"Number of duplicate rows (including first occurrence): {num_duplicates}")

Number of duplicate rows (including first occurrence): 0

In [21]:
duplicates_mask_1 = cases_df.duplicated(subset=["Anonymized_Temporal", "Assessment_Date", "Episode_Date"], keep=False)
num_duplicates_1 = duplicates_mask_1.sum()

print(f"Number of duplicate rows (including first occurrence): {num_duplicates_1}")

Number of duplicate rows (including first occurrence): 0

In [22]:
# Look for duplicates
# Get the rows that are duplicates
duplicates = cases_df[duplicates_mask]

# Sort them to see duplicates grouped together
duplicates_sorted = duplicates.sort_values(by=["Anonymized_Temporal", "Assessment_Date", "Episode_Date"])

# Display
duplicates_sorted[["Anonymized_Temporal", "Assessment_Date", "Episode_Date"]].head(25)

Empty DataFrame
Columns: [Anonymized_Temporal, Assessment_Date, Episode_Date]
Index: []

In [24]:
cases_df.columns

Index(['Anonymized_Temporal', 'RC', 'Reason_for_Consultation', 'Episode',
       'Episode_Date', 'Sex', 'DoB', 'Assessment_Date', 'Psychiatric_History',
       'Medical_History', 'Subjective_Impressions', 'Grade',
       'Recent_Suicidal_Planning', 'Grade_A', 'EJEI_Coded_Diagnostic_CIE',
       'EJEI_Diagnostic', 'Medical_Damage_Severity_From_Current_Attempt',
       'Family_History_of_Suicide_Attempts',
       'EJEI_Personality_and_Behavior_Disorder_L',
       'EJEI_Personality_and_Behavior_Disorder', 'Recent_Suicidal_Ideation',
       'EJEI_Somatic_Disorder_Cod1', 'EJEI_Somatic_Disorder_Text',
       'Number_of_Previous_Suicide_Attempts',
       'EJEI_Psychosocial_and_Environmental_Issues', 'Discharge_Treatment',
       'Psychopathological_Examination', 'Last_Episode', 'Num_Episodes'],
      dtype='object')

Store the df in an excel ready to be processed by the annotation and normalization pipeline.

In [25]:
cases_df.to_excel(os.path.join(directory_path, "data", "ace_confirmed_100_cases.xlsx"), index=False)